### ISSUE TITLE
Does not work presently

### ISSUE THREAD

**Issue by ChristopherDavenport** [http4s/http4s.g8#160] opened 2020-08-27 21:11 UTC
```

Exiting due to error in the template
relative: $if(graal_native_image.truthy)$native-image-readme.md$endif$, toPath: ./quickstart, context [anonymous] 1:4 internal error: org.stringtemplate.v4.compiler.STException: context [anonymous] 1:4 no such property or can't access: java.lang.String.truthy
Caused by: org.stringtemplate.v4.misc.STNoSuchPropertyException: no such property: java.lang.String.truthy
	at org.stringtemplate.v4.misc.ObjectModelAdaptor.throwNoSuchProperty(ObjectModelAdaptor.java:167)
	at org.stringtemplate.v4.misc.ObjectModelAdaptor.getProperty(ObjectModelAdaptor.java:89)
	at org.stringtemplate.v4.Interpreter.getObjectProperty(Interpreter.java:1200)
	at org.stringtemplate.v4.Interpreter._exec(Interpreter.java:210)
	at org.stringtemplate.v4.Interpreter.exec(Interpreter.java:145)
	at org.stringtemplate.v4.ST.write(ST.java:427)
	at org.stringtemplate.v4.ST.render(ST.java:497)
	at org.clapper.scalasti.ST.render(ST.scala:285)
	at giter8.G8$.applyTemplate(g8.scala:102)
	at giter8.G8$.expandPath(g8.scala:176)
	at giter8.G8$$anonfun$writeTemplates$1.apply(g8.scala:384)
	at giter8.G8$$anonfun$writeTemplates$1.apply(g8.scala:382)
	at scala.collection.immutable.Stream.map(Stream.scala:376)
	at giter8.G8$.writeTemplates(g8.scala:382)
	at giter8.G8$$anonfun$applyT$1.apply(g8.scala:256)
	at giter8.G8$$anonfun$applyT$1.apply(g8.scala:249)
	at scala.util.Either$RightProjection.flatMap(Either.scala:523)
	at giter8.G8$.applyT(g8.scala:249)
	at giter8.G8$.fromDirectory(g8.scala:62)
	at giter8.JgitHelper$$anonfun$run$2.apply(JgitHelper.scala:69)
	at giter8.JgitHelper$$anonfun$run$2.apply(JgitHelper.scala:68)
	at scala.util.Either$RightProjection.flatMap(Either.scala:523)
	at giter8.JgitHelper$.run(JgitHelper.scala:68)
	at giter8.JgitHelper$.run(JgitHelper.scala:80)
	at giter8.Giter8$$anonfun$2.apply(giter8.scala:34)
	at giter8.Giter8$$anonfun$2.apply(giter8.scala:33)
	at scala.Option.map(Option.scala:145)
	at giter8.Giter8.run(giter8.scala:33)
	at sbtgiter8resolver.Giter8TemplateResolver.run(Giter8TemplateResolver.scala:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sbt.TemplateCommandUtil$.call(TemplateCommand.scala:68)
	at sbt.TemplateCommandUtil$.sbt$TemplateCommandUtil$$runTemplate(TemplateCommand.scala:59)
	at sbt.TemplateCommandUtil$$anonfun$2.apply(TemplateCommand.scala:45)
	at sbt.TemplateCommandUtil$$anonfun$2.apply(TemplateCommand.scala:41)
	at scala.collection.LinearSeqOptimized$class.find(LinearSeqOptimized.scala:100)
	at scala.collection.immutable.List.find(List.scala:84)
	at sbt.TemplateCommandUtil$.sbt$TemplateCommandUtil$$run(TemplateCommand.scala:41)
	at sbt.TemplateCommandUtil$$anonfun$templateCommandParser$1.apply(TemplateCommand.scala:34)
	at sbt.TemplateCommandUtil$$anonfun$templateCommandParser$1.apply(TemplateCommand.scala:28)
	at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:61)
	at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:61)
	at sbt.Command$.process(Command.scala:93)
	at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:96)
	at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:96)
	at sbt.State$$anon$1.runCmd$1(State.scala:183)
	at sbt.State$$anon$1.process(State.scala:187)
	at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:96)
	at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:96)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.MainLoop$.next(MainLoop.scala:96)
	at sbt.MainLoop$.run(MainLoop.scala:89)
	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:68)
	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:63)
	at sbt.Using.apply(Using.scala:24)
	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:63)
	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:46)
	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:30)
	at sbt.MainLoop$.runLogged(MainLoop.scala:22)
	at sbt.StandardMain$.runManaged(Main.scala:61)
	at sbt.xMain.run(Main.scala:35)
	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
	at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
	at xsbt.boot.Launch$.run(Launch.scala:109)
	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
	at xsbt.boot.Launch$.launch(Launch.scala:117)
	at xsbt.boot.Launch$.apply(Launch.scala:18)
	at xsbt.boot.Boot$.runImpl(Boot.scala:41)
	at xsbt.boot.Boot$.main(Boot.scala:17)
	at xsbt.boot.Boot.main(Boot.scala)

	at giter8.G8$STErrorHandler.runTimeError(g8.scala:110)
	at giter8.G8$STErrorHandler.runTimeError(g8.scala:105)
	at org.stringtemplate.v4.misc.ErrorManager.runTimeError(ErrorManager.java:137)
	at org.stringtemplate.v4.Interpreter.getObjectProperty(Interpreter.java:1203)
	at org.stringtemplate.v4.Interpreter._exec(Interpreter.java:210)
	at org.stringtemplate.v4.Interpreter.exec(Interpreter.java:145)
	at org.stringtemplate.v4.ST.write(ST.java:427)
	at org.stringtemplate.v4.ST.render(ST.java:497)
	at org.clapper.scalasti.ST.render(ST.scala:285)
	at giter8.G8$.applyTemplate(g8.scala:102)
	at giter8.G8$.expandPath(g8.scala:176)
	at giter8.G8$$anonfun$writeTemplates$1.apply(g8.scala:384)
	at giter8.G8$$anonfun$writeTemplates$1.apply(g8.scala:382)
	at scala.collection.immutable.Stream.map(Stream.scala:376)
	at giter8.G8$.writeTemplates(g8.scala:382)
	at giter8.G8$$anonfun$applyT$1.apply(g8.scala:256)
	at giter8.G8$$anonfun$applyT$1.apply(g8.scala:249)
	at scala.util.Either$RightProjection.flatMap(Either.scala:523)
	at giter8.G8$.applyT(g8.scala:249)
	at giter8.G8$.fromDirectory(g8.scala:62)
	at giter8.JgitHelper$$anonfun$run$2.apply(JgitHelper.scala:69)
	at giter8.JgitHelper$$anonfun$run$2.apply(JgitHelper.scala:68)
	at scala.util.Either$RightProjection.flatMap(Either.scala:523)
	at giter8.JgitHelper$.run(JgitHelper.scala:68)
	at giter8.JgitHelper$.run(JgitHelper.scala:80)
	at giter8.Giter8$$anonfun$2.apply(giter8.scala:34)
	at giter8.Giter8$$anonfun$2.apply(giter8.scala:33)
	at scala.Option.map(Option.scala:145)
	at giter8.Giter8.run(giter8.scala:33)
	at sbtgiter8resolver.Giter8TemplateResolver.run(Giter8TemplateResolver.scala:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sbt.TemplateCommandUtil$.call(TemplateCommand.scala:68)
	at sbt.TemplateCommandUtil$.sbt$TemplateCommandUtil$$runTemplate(TemplateCommand.scala:59)
	at sbt.TemplateCommandUtil$$anonfun$2.apply(TemplateCommand.scala:45)
	at sbt.TemplateCommandUtil$$anonfun$2.apply(TemplateCommand.scala:41)
	at scala.collection.LinearSeqOptimized$class.find(LinearSeqOptimized.scala:100)
	at scala.collection.immutable.List.find(List.scala:84)
	at sbt.TemplateCommandUtil$.sbt$TemplateCommandUtil$$run(TemplateCommand.scala:41)
	at sbt.TemplateCommandUtil$$anonfun$templateCommandParser$1.apply(TemplateCommand.scala:34)
	at sbt.TemplateCommandUtil$$anonfun$templateCommandParser$1.apply(TemplateCommand.scala:28)
	at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:61)
	at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:61)
	at sbt.Command$.process(Command.scala:93)
	at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:96)
	at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:96)
	at sbt.State$$anon$1.runCmd$1(State.scala:183)
	at sbt.State$$anon$1.process(State.scala:187)
	at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:96)
	at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:96)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.MainLoop$.next(MainLoop.scala:96)
	at sbt.MainLoop$.run(MainLoop.scala:89)
	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:68)
	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:63)
	at sbt.Using.apply(Using.scala:24)
	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:63)
	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:46)
	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:30)
	at sbt.MainLoop$.runLogged(MainLoop.scala:22)
	at sbt.StandardMain$.runManaged(Main.scala:61)
	at sbt.xMain.run(Main.scala:35)
	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
	at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
	at xsbt.boot.Launch$.run(Launch.scala:109)
	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
	at xsbt.boot.Launch$.launch(Launch.scala:117)
	at xsbt.boot.Launch$.apply(Launch.scala:18)
	at xsbt.boot.Boot$.runImpl(Boot.scala:41)
	at xsbt.boot.Boot$.main(Boot.scala:17)
	at xsbt.boot.Boot.main(Boot.scala)
```

Uh-oh.

**Comment by DanielaSfregola** [comment] 2020-10-17 09:38
This seems to be a gitter8 bug, which has been fixed and included in a recent SBT reversion - see https://github.com/http4s/http4s.g8/issues/144#issuecomment-636762694

so running it with sbt 1.3.12 fixed it for me :)

```
sbt -sbt-version 1.3.12 new http4s/http4s.g8
```

**Comment by rossabaker** [comment] 2020-10-18 04:37
I thought this was fixed by upgrading to sbt-1.4.0, but looking again, maybe it's the client version that matters?  Is this an http4s docs issue?

**Comment by DanielaSfregola** [comment] 2020-10-18 08:29
I think the problem is the SBT launcher - this is a client problem, not any of the parameters in the gitter8 template.

In fact, I can just type the following:

```
Danielas-MacBook-Pro:test danielasfregola$ sbt -sbt-version 1.3.12
[warn] No sbt.version set in project/build.properties, base directory: /Users/danielasfregola/Development/get-programming-with-scala/unit8/test
[info] welcome to sbt 1.3.12 (Oracle Corporation Java 1.8.0_60)
[info] loading settings for project global-plugins from idea.sbt,metals.sbt ...
[info] loading global plugins from /Users/danielasfregola/.sbt/1.0/plugins
[info] set current project to test (in build file:/Users/danielasfregola/Development/get-programming-with-scala/unit8/test/)
[info] sbt server started at local:///Users/danielasfregola/.sbt/1.0/server/cf7d7086fe4c8798cee5/sock
sbt:test> 
```

You can clearly see what is trying to run if you put a crazy version in:
```
Danielas-MacBook-Pro:test danielasfregola$ sbt -sbt-version 99.99.99
Getting org.scala-sbt sbt 99.99.99  (this may take some time)...

:: problems summary ::
:::: WARNINGS
		module not found: org.scala-sbt#sbt;99.99.99

	==== local: tried

	  /Users/danielasfregola/.ivy2/local/org.scala-sbt/sbt/99.99.99/ivys/ivy.xml

	  -- artifact org.scala-sbt#sbt;99.99.99!sbt.jar:

	  /Users/danielasfregola/.ivy2/local/org.scala-sbt/sbt/99.99.99/jars/sbt.jar

	==== local-preloaded-ivy: tried

	  file:////Users/danielasfregola/.sbt/preloaded/org.scala-sbt/sbt/99.99.99/ivys/ivy.xml

	==== local-preloaded: tried

	  file:////Users/danielasfregola/.sbt/preloaded/org/scala-sbt/sbt/99.99.99/sbt-99.99.99.pom

	  -- artifact org.scala-sbt#sbt;99.99.99!sbt.jar:

	  file:////Users/danielasfregola/.sbt/preloaded/org/scala-sbt/sbt/99.99.99/sbt-99.99.99.jar

	==== Maven Central: tried

	  https://repo1.maven.org/maven2/org/scala-sbt/sbt/99.99.99/sbt-99.99.99.pom

	  -- artifact org.scala-sbt#sbt;99.99.99!sbt.jar:

	  https://repo1.maven.org/maven2/org/scala-sbt/sbt/99.99.99/sbt-99.99.99.jar

	==== sbt-maven-releases: tried

	  https://repo.scala-sbt.org/scalasbt/maven-releases/org/scala-sbt/sbt/99.99.99/sbt-99.99.99.pom

	  -- artifact org.scala-sbt#sbt;99.99.99!sbt.jar:

	  https://repo.scala-sbt.org/scalasbt/maven-releases/org/scala-sbt/sbt/99.99.99/sbt-99.99.99.jar

	==== sbt-maven-snapshots: tried

	  https://repo.scala-sbt.org/scalasbt/maven-snapshots/org/scala-sbt/sbt/99.99.99/sbt-99.99.99.pom

	  -- artifact org.scala-sbt#sbt;99.99.99!sbt.jar:

	  https://repo.scala-sbt.org/scalasbt/maven-snapshots/org/scala-sbt/sbt/99.99.99/sbt-99.99.99.jar

	==== typesafe-ivy-releases: tried

	  https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt/99.99.99/ivys/ivy.xml

	==== sbt-ivy-snapshots: tried

	  https://repo.scala-sbt.org/scalasbt/ivy-snapshots/org.scala-sbt/sbt/99.99.99/ivys/ivy.xml

		::::::::::::::::::::::::::::::::::::::::::::::

		::          UNRESOLVED DEPENDENCIES         ::

		::::::::::::::::::::::::::::::::::::::::::::::

		:: org.scala-sbt#sbt;99.99.99: not found

		::::::::::::::::::::::::::::::::::::::::::::::



:: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS
unresolved dependency: org.scala-sbt#sbt;99.99.99: not found
Error during sbt execution: Error retrieving required libraries
  (see /Users/danielasfregola/.sbt/boot/update.log for complete log)
Error: Could not retrieve sbt 99.99.99
```

**Comment by rossabaker** [comment] 2020-10-18 21:09
I was concerned about the version in our quickstart, but we already have that pointing to a working version, and those who hit it anyway will hopefully find one of the tickets about it. Thanks for hunting down the cause!

**Closed as completed by rossabaker** 2020-10-18 21:09 UTC
